version: "3.8"

services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/code
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: npm start
